name: DOTNET Cover

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore 
          
      
      
    - name: Test
      run: dotnet test 
    
    - name: dotnet cover  
      uses: dodopizza/dotcover-action@v1
      with:
         #dotCoverCommand: help cover coverage.xml
         dotCoverCommand: dotnet --output=AppCoverageReport.html --reportType=HTML -- test "./unit-testing-using-nunit.csproj"

       

 
    - name: 'Publish code coverage results'
      uses: actions/upload-artifact@v2.2.3
      with:
          name: CoverageReport
          path: ${{github.workspace}}/coverage.xml 
